/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { PlaidIntegration } from "./PlaidIntegration";
import { PlaidIntegrationCountArgs } from "./PlaidIntegrationCountArgs";
import { PlaidIntegrationFindManyArgs } from "./PlaidIntegrationFindManyArgs";
import { PlaidIntegrationFindUniqueArgs } from "./PlaidIntegrationFindUniqueArgs";
import { CreatePlaidIntegrationArgs } from "./CreatePlaidIntegrationArgs";
import { UpdatePlaidIntegrationArgs } from "./UpdatePlaidIntegrationArgs";
import { DeletePlaidIntegrationArgs } from "./DeletePlaidIntegrationArgs";
import { User } from "../../user/base/User";
import { PlaidIntegrationService } from "../plaidIntegration.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PlaidIntegration)
export class PlaidIntegrationResolverBase {
  constructor(
    protected readonly service: PlaidIntegrationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PlaidIntegration",
    action: "read",
    possession: "any",
  })
  async _plaidIntegrationsMeta(
    @graphql.Args() args: PlaidIntegrationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PlaidIntegration])
  @nestAccessControl.UseRoles({
    resource: "PlaidIntegration",
    action: "read",
    possession: "any",
  })
  async plaidIntegrations(
    @graphql.Args() args: PlaidIntegrationFindManyArgs
  ): Promise<PlaidIntegration[]> {
    return this.service.plaidIntegrations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PlaidIntegration, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PlaidIntegration",
    action: "read",
    possession: "own",
  })
  async plaidIntegration(
    @graphql.Args() args: PlaidIntegrationFindUniqueArgs
  ): Promise<PlaidIntegration | null> {
    const result = await this.service.plaidIntegration(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PlaidIntegration)
  @nestAccessControl.UseRoles({
    resource: "PlaidIntegration",
    action: "create",
    possession: "any",
  })
  async createPlaidIntegration(
    @graphql.Args() args: CreatePlaidIntegrationArgs
  ): Promise<PlaidIntegration> {
    return await this.service.createPlaidIntegration({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PlaidIntegration)
  @nestAccessControl.UseRoles({
    resource: "PlaidIntegration",
    action: "update",
    possession: "any",
  })
  async updatePlaidIntegration(
    @graphql.Args() args: UpdatePlaidIntegrationArgs
  ): Promise<PlaidIntegration | null> {
    try {
      return await this.service.updatePlaidIntegration({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PlaidIntegration)
  @nestAccessControl.UseRoles({
    resource: "PlaidIntegration",
    action: "delete",
    possession: "any",
  })
  async deletePlaidIntegration(
    @graphql.Args() args: DeletePlaidIntegrationArgs
  ): Promise<PlaidIntegration | null> {
    try {
      return await this.service.deletePlaidIntegration(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(
    @graphql.Parent() parent: PlaidIntegration
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
